{% set name = "gron" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomnomnom/gron/archive/v{{ version }}.tar.gz
  sha256: 1c98f2ef2ba03558864b1ab5e9c4b47a2e89d3ffaf24cfa0ac75cd38d775feb4

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gron --help

about:
  home: https://github.com/tomnomnom/gron
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Make JSON greppable
  dev_url: https://github.com/tomnomnom/gron

extra:
  recipe-maintainers:
    - danielnachun
